# Generated by Django 5.2.13 on 2026-04-30 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название тега')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1028, verbose_name='Заголовок вопроса')),
                ('description', models.TextField(verbose_name='Описание вопроса')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('vote_count', models.IntegerField(default=0, verbose_name='Рейтинг голосов ↑ / ↓')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(verbose_name='Текст ответа')),
                ('creation_time', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Выбран ли автором как правильный')),
                ('vote_count', models.IntegerField(default=0, verbose_name='Рейтинг голосов ↑ / ↓')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.CreateModel(
            name='AnswerVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[(1, 'Голос вверх'), (-1, 'Голос вниз')], verbose_name='Значение голоса')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.answer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Голос за ответ',
                'verbose_name_plural': 'Голоса за ответ',
                'unique_together': {('answer', 'user')},
            },
        ),
        migrations.CreateModel(
            name='QuestionVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(choices=[(1, 'Голос вверх'), (-1, 'Голос вниз')], verbose_name='Значение голоса')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Голос за вопрос',
                'verbose_name_plural': 'Голоса за вопрос',
                'unique_together': {('question', 'user')},
            },
        ),
        migrations.CreateModel(
            name='QuestionTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.tag')),
            ],
            options={
                'verbose_name': 'Связь вопросы-теги',
                'verbose_name_plural': 'Связи вопросы-теги',
                'unique_together': {('question', 'tag')},
            },
        ),
    ]
